input {
  beats { port => 5044 }
}

filter {
  json { source => "message" skip_on_invalid_json => true }
  mutate { add_field => { "env" => "prod" } }
}

output {
  elasticsearch {
    hosts => ["elasticsearch.logging.svc.cluster.local:9200"]
    index => "porttrack-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ES_PASSWORD}"
  }
}